export const POST_PRODUCT_DATA = 'POST_PRODUCT_DATA';

export const GET_PRODUCTS_DATA = 'GET_PRODUCTS_DATA';
export const GET_PRODUCTS_DATA_SUCCESS = 'GET_PRODUCTS_DATA_SUCCESS';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
